const ActionTypes = {
    USERNAME: 'USERNAME',
    CURRENTUSER: 'CURRENTUSER',
    ALLUSERS: 'ALLUSERS',
    MESSAGES: 'MESSAGES',
    CHANGERECPUID: 'CHANGERECPUID',
    UPDATEPORTFOLIO: 'UPDATEPORTFOLIO',
    SHOW_MESSAGES: 'SHOW_MESSAGES',
    LOGIN: 'LOGIN',
    JOBS: 'JOBS',
    STUDENTS: 'STUDENTS',
    COMPANIES: 'COMPANIES',
    ALL_JOBS: 'ALL_JOBS',
    APPLICANTS: 'APPLICANTS'
}

export default ActionTypes;
